Optimization to StrStartsWith function
ontop/ontop pull request #801
Opened 2024-04-24 15:12 UTC by ManuelaCorte

This optimization allows to simplify the `STRSTARTS` SPARQL function when the second argument is a constant and the first argument is either:
- **constant**: the two constants values can be directly compared
- **iri template**: the iri template prefix can be compared with the second argument value

### Motivating Example

Query to partially materialize the Ontopic Data Hub dataset into GraphDB that caused the underlying PostgreSQL database to crash:
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
INSERT {
  GRAPH <http://example.com/materialized-simple-mapping-query> {
    ?s ?p ?o .
  }
}
WHERE {
  SERVICE <http://172.17.0.1:8080/sparql> {
    ?s ?p ?o .
    FILTER (!STRSTARTS(STR(?s), "https://kg.opendatahub.bz.it/data/observation/"))
  }
}
```

### Optimization Example
```
PREFIX ex: <http://www.example.org/>
SELECT DISTINCT ?s
WHERE {
  ?s ?p ?o.
  FILTER (STRSTARTS(STR(?s), "http://www.example.org/Re"))
}
```
which has as result all triples associated with the `Result`entity
|   	| Results                         	|
|---	|---------------------------------	|
| 1 	| http://www.example.org/Result/1 	|
| 2 	| http://www.example.org/Result/2 	|

 
This query is equivalent to the following unfolded `IQTree`:
```
DISTINCT
   CONSTRUCT [s] []
      FILTER RDF_2_DB_BOOL(SP_STARTS_WITH(SP_STR(s),"http://www.example.org/Re"))
         CONSTRUCT [s, p, o] [s/RDF(v5,IRI), p/RDF(v9,IRI), o/RDF(v18,v19)]
            UNION [v5, v9, v18, v19]
               CONSTRUCT [v5, v9, v18, v19] [v9/"http://www.w3.org/1999/02/22-rdf-syntax-ns#type"^^TEXT, v18/"http://www.example.org/Person"^^TEXT, v19/IRI, v5/http://www.example.org/Person/{}(INTEGERToTEXT(PERSON_ID1m1))]
                  EXTENSIONAL "PERSON"(0:PERSON_ID1m1)
               CONSTRUCT [v5, v9, v18, v19] [v9/"http://www.w3.org/1999/02/22-rdf-syntax-ns#type"^^TEXT, v18/"http://www.example.org/House"^^TEXT, v19/IRI, v5/http://www.example.org/House/{}(INTEGERToTEXT(HOUSE_ID1m3))]
                  EXTENSIONAL "HOUSE"(0:HOUSE_ID1m3)
               CONSTRUCT [v5, v9, v18, v19] [v9/"http://www.w3.org/1999/02/22-rdf-syntax-ns#type"^^TEXT, v18/"http://www.example.org/Result"^^TEXT, v19/IRI, v5/http://www.example.org/Result/{}(INTEGERToTEXT(SENSOR_ID1m6))]
                  EXTENSIONAL "SENSOR"(0:SENSOR_ID1m6)
               CONSTRUCT [v5, v9, v18, v19] [v9/"http://www.example.org/givenName"^^TEXT, v18/CHARACTER VARYINGToTEXT(FIRST_NAME1m2), v19/xsd:string, v5/http://www.example.org/Person/{}(INTEGERToTEXT(PERSON_ID1m2))]
                  FILTER IS_NOT_NULL(FIRST_NAME1m2)
                     EXTENSIONAL "PERSON"(0:PERSON_ID1m2,1:FIRST_NAME1m2)
               CONSTRUCT [v5, v9, v18, v19] [v9/"http://www.example.org/address"^^TEXT, v18/CHARACTER VARYINGToTEXT(ADDRESS1m4), v19/xsd:string, v5/http://www.example.org/House/{}(INTEGERToTEXT(HOUSE_ID1m4))]
                  EXTENSIONAL "HOUSE"(0:HOUSE_ID1m4,1:ADDRESS1m4)
               CONSTRUCT [v5, v9, v18, v19] [v9/"http://www.example.org/belongs"^^TEXT, v18/http://www.example.org/Person/{}(INTEGERToTEXT(OWNER1m5)), v19/IRI, v5/http://www.example.org/House/{}(INTEGERToTEXT(HOUSE_ID1m5))]
                  FILTER IS_NOT_NULL(OWNER1m5)
                     EXTENSIONAL "HOUSE"(0:HOUSE_ID1m5,2:OWNER1m5)
               CONSTRUCT [v5, v9, v18, v19] [v9/"http://www.example.org/hasTimestamp"^^TEXT, v18/CHARACTER VARYINGToTEXT(TIMESTAMP1m7), v19/xsd:dateTime, v5/http://www.example.org/Result/{}(INTEGERToTEXT(SENSOR_ID1m7))]
                  EXTENSIONAL "SENSOR"(0:SENSOR_ID1m7,1:TIMESTAMP1m7)
```
Since the filter is applied on the triples subjects (which are always IRIs), `STRSTARTS` is optimized: all IRIs for the `Person`and `House` entities (respectively `http://www.example.org/Person/{person_id}` and `http://www.example.org/House/{house_id}`) don´t match the `"http://www.example.org/Re"` prefix, and thus the associated nodes are removed from the IQTree, while the ones associated with the `Result`entity (`http://www.example.org/Result/{result_id}`) are kept. 
```
CONSTRUCT [s] [s/RDF(http://www.example.org/Result/{}(INTEGERToTEXT(SENSOR_ID1m0)),IRI)]
   DISTINCT
      UNION [SENSOR_ID1m0]
         EXTENSIONAL "SENSOR"(0:SENSOR_ID1m0)
         EXTENSIONAL "SENSOR"(0:SENSOR_ID1m0)
```

2024-04-29 06:18 UTC, bcogrel requested changes
Thanks @ManuelaCorte ! Just some minor cleaning and we are good to go. 
Could you please have a look at my comments?

2024-04-29 06:18 UTC, bcogrel commented on binding/rdf4j/src/test/java/it/unibz/inf/ontop/rdf4j/repository/StrStartsFunctionTest.java
> +                ImmutableMap.of("s", "http://www.schema.org/Person/1"),
Could you please use a different prefix for the data? Schema.org, SOSA (in your PR description) are intended to be only for the ontology, not the data we map.

2024-04-29 06:18 UTC, bcogrel commented on binding/rdf4j/src/test/resources/strstarts-function/sparql-strstarts.sql
> +    house_id integer NOT NULL,
Please a unique constraint (or a primary key). This is standard practice and will clean your examples from distincts.

2024-04-29 06:18 UTC, bcogrel commented on binding/rdf4j/src/test/resources/strstarts-function/sparql-strstarts.sql
> +    sensor_id integer NOT NULL,
Same here about the unique constraint

2024-04-29 06:18 UTC, bcogrel commented on core/model/src/main/java/it/unibz/inf/ontop/model/term/functionsymbol/db/impl/DefaultDBStrStartsWithFunctionSymbol.java
> +                ImmutableFunctionalTerm firstNonFunctionalTerm = (ImmutableFunctionalTerm) newTerms.get(0);
Please rename the variable (it is actually functional) into `firstFunctionalTerm`

2024-04-30 07:34 UTC, ManuelaCorte commented
Hi Benjamin, thanks for the corrections! Below I've updated the PR description to follow your suggestions.

This optimization allows to simplify the `STRSTARTS` SPARQL function when the second argument is a constant and the first argument is either:
- **constant**: the two constants values can be directly compared
- **iri template**: the iri template prefix can be compared with the second argument value

### Motivating Example

Query to partially materialize the Ontopic Data Hub dataset into GraphDB that caused the underlying PostgreSQL database to crash:
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
INSERT {
  GRAPH <http://example.com/materialized-simple-mapping-query> {
    ?s ?p ?o .
  }
}
WHERE {
  SERVICE <http://172.17.0.1:8080/sparql> {
    ?s ?p ?o .
    FILTER (!STRSTARTS(STR(?s), "https://kg.opendatahub.bz.it/data/observation/"))
  }
}
```

### Optimization Example
```
PREFIX ex: <http://www.example.org/>
SELECT DISTINCT ?s
WHERE {
  ?s ?p ?o.
  FILTER (STRSTARTS(STR(?s), "http://www.example.org/Re"))
}
```
which has as result all triples associated with the `Result`entity
|   	| Results                         	|
|---	|---------------------------------	|
| 1 	| http://www.example.org/Result/1 	|
| 2 	| http://www.example.org/Result/2 	|

 
This query is equivalent to the following unfolded `IQTree`:
```
DISTINCT
   CONSTRUCT [s] []
      FILTER RDF_2_DB_BOOL(SP_STARTS_WITH(SP_STR(s),"http://www.example.org/Re"))
         CONSTRUCT [s, p, o] [s/RDF(v5,IRI), p/RDF(v9,IRI), o/RDF(v18,v19)]
            UNION [v5, v9, v18, v19]
               CONSTRUCT [v5, v9, v18, v19] [v9/"http://www.w3.org/1999/02/22-rdf-syntax-ns#type"^^TEXT, v18/"http://www.example.org/Person"^^TEXT, v19/IRI, v5/http://www.example.org/Person/{}(INTEGERToTEXT(PERSON_ID1m1))]
                  EXTENSIONAL "PERSON"(0:PERSON_ID1m1)
               CONSTRUCT [v5, v9, v18, v19] [v9/"http://www.w3.org/1999/02/22-rdf-syntax-ns#type"^^TEXT, v18/"http://www.example.org/House"^^TEXT, v19/IRI, v5/http://www.example.org/House/{}(INTEGERToTEXT(HOUSE_ID1m3))]
                  EXTENSIONAL "HOUSE"(0:HOUSE_ID1m3)
               CONSTRUCT [v5, v9, v18, v19] [v9/"http://www.w3.org/1999/02/22-rdf-syntax-ns#type"^^TEXT, v18/"http://www.example.org/Result"^^TEXT, v19/IRI, v5/http://www.example.org/Result/{}(INTEGERToTEXT(SENSOR_ID1m6))]
                  EXTENSIONAL "SENSOR"(0:SENSOR_ID1m6)
               CONSTRUCT [v5, v9, v18, v19] [v9/"http://www.example.org/givenName"^^TEXT, v18/CHARACTER VARYINGToTEXT(FIRST_NAME1m2), v19/xsd:string, v5/http://www.example.org/Person/{}(INTEGERToTEXT(PERSON_ID1m2))]
                  FILTER IS_NOT_NULL(FIRST_NAME1m2)
                     EXTENSIONAL "PERSON"(0:PERSON_ID1m2,1:FIRST_NAME1m2)
               CONSTRUCT [v5, v9, v18, v19] [v9/"http://www.example.org/address"^^TEXT, v18/CHARACTER VARYINGToTEXT(ADDRESS1m4), v19/xsd:string, v5/http://www.example.org/House/{}(INTEGERToTEXT(HOUSE_ID1m4))]
                  EXTENSIONAL "HOUSE"(0:HOUSE_ID1m4,1:ADDRESS1m4)
               CONSTRUCT [v5, v9, v18, v19] [v9/"http://www.example.org/belongs"^^TEXT, v18/http://www.example.org/Person/{}(INTEGERToTEXT(OWNER1m5)), v19/IRI, v5/http://www.example.org/House/{}(INTEGERToTEXT(HOUSE_ID1m5))]
                  FILTER IS_NOT_NULL(OWNER1m5)
                     EXTENSIONAL "HOUSE"(0:HOUSE_ID1m5,2:OWNER1m5)
               CONSTRUCT [v5, v9, v18, v19] [v9/"http://www.example.org/hasTimestamp"^^TEXT, v18/CHARACTER VARYINGToTEXT(TIMESTAMP1m7), v19/xsd:dateTime, v5/http://www.example.org/Result/{}(INTEGERToTEXT(SENSOR_ID1m7))]
                  EXTENSIONAL "SENSOR"(0:SENSOR_ID1m7,1:TIMESTAMP1m7)
```
Since the filter is applied on the triples subjects (which are always IRIs), `STRSTARTS` is optimized: all IRIs for the `Person`and `House` entities (respectively `http://www.example.org/Person/{person_id}` and `http://www.example.org/House/{house_id}`) don´t match the `"http://www.example.org/Re"` prefix, and thus the associated nodes are removed from the IQTree, while the ones associated with the `Result`entity (`http://www.example.org/Result/{result_id}`) are kept. 
```
CONSTRUCT [s] [s/RDF(http://www.example.org/Result/{}(INTEGERToTEXT(SENSOR_ID1m0)),IRI)]
   DISTINCT
      UNION [SENSOR_ID1m0]
         EXTENSIONAL "SENSOR"(0:SENSOR_ID1m0)
         EXTENSIONAL "SENSOR"(0:SENSOR_ID1m0)
```

2024-04-30 14:04 UTC, merged

2024-04-30 14:04 UTC, bcogrel commented
Many thanks Manuela!